import type { Bank } from "./types"

export const US_BANKS: Bank[] = [
  {
    rank: 1,
    name: "JPMORGAN CHASE BK NA",
    holdingCompany: "JPMORGAN CHASE & CO",
    location: "COLUMBUS, OH",
    charter: "NAT",
    consolidatedAssets: 3813431,
    domesticAssets: 2747665,
    type: "bank",
    country: "US",
  },
  {
    rank: 2,
    name: "BANK OF AMER NA",
    holdingCompany: "BANK OF AMER CORP",
    location: "CHARLOTTE, NC",
    charter: "NAT",
    consolidatedAssets: 2651090,
    domesticAssets: 2491192,
    type: "bank",
    country: "US",
  },
  {
    rank: 3,
    name: "CITIBANK NA",
    holdingCompany: "CITIGROUP",
    location: "SIOUX FALLS, SD",
    charter: "NAT",
    consolidatedAssets: 1844189,
    domesticAssets: 1107837,
    type: "bank",
    country: "US",
  },
  {
    rank: 4,
    name: "WELLS FARGO BK NA",
    holdingCompany: "WELLS FARGO & CO",
    location: "SIOUX FALLS, SD",
    charter: "NAT",
    consolidatedAssets: 1767105,
    domesticAssets: 1757039,
    type: "bank",
    country: "US",
  },
  {
    rank: 5,
    name: "U S BK NA",
    holdingCompany: "U S BC",
    location: "CINCINNATI, OH",
    charter: "NAT",
    consolidatedAssets: 679293,
    domesticAssets: 671238,
    type: "bank",
    country: "US",
  },
  {
    rank: 6,
    name: "CAPITAL ONE NA",
    holdingCompany: "CAPITAL ONE FC",
    location: "MC LEAN, VA",
    charter: "NAT",
    consolidatedAssets: 652138,
    domesticAssets: 651634,
    type: "bank",
    country: "US",
  },
  {
    rank: 7,
    name: "GOLDMAN SACHS BK USA",
    holdingCompany: "GOLDMAN SACHS GROUP THE",
    location: "NEW YORK, NY",
    charter: "SMB",
    consolidatedAssets: 644020,
    domesticAssets: 540971,
    type: "bank",
    country: "US",
  },
  {
    rank: 8,
    name: "PNC BK NA",
    holdingCompany: "PNC FNCL SVC GROUP",
    location: "WILMINGTON, DE",
    charter: "NAT",
    consolidatedAssets: 563953,
    domesticAssets: 558832,
    type: "bank",
    country: "US",
  },
  {
    rank: 9,
    name: "TRUIST BK",
    holdingCompany: "TRUIST FC",
    location: "CHARLOTTE, NC",
    charter: "SNM",
    consolidatedAssets: 535540,
    domesticAssets: 535378,
    type: "bank",
    country: "US",
  },
  {
    rank: 10,
    name: "BANK OF NY MELLON",
    holdingCompany: "BANK OF NY MELLON CORP",
    location: "NEW YORK, NY",
    charter: "SMB",
    consolidatedAssets: 366502,
    domesticAssets: 268122,
    type: "bank",
    country: "US",
  },
  {
    rank: 11,
    name: "STATE STREET B&TC",
    holdingCompany: "STATE STREET CORP",
    location: "BOSTON, MA",
    charter: "SMB",
    consolidatedAssets: 366079,
    domesticAssets: 278551,
    type: "bank",
    country: "US",
  },
  {
    rank: 12,
    name: "TD BK NA",
    holdingCompany: "TD GRP US HOLDS LLC",
    location: "WILMINGTON, DE",
    charter: "NAT",
    consolidatedAssets: 350852,
    domesticAssets: 350852,
    type: "bank",
    country: "US",
  },
  {
    rank: 13,
    name: "MORGAN STANLEY BK NA",
    holdingCompany: "MORGAN STANLEY",
    location: "SALT LAKE CITY, UT",
    charter: "NAT",
    consolidatedAssets: 249681,
    domesticAssets: 249681,
    type: "bank",
    country: "US",
  },
  {
    rank: 14,
    name: "BMO BK NA",
    holdingCompany: "BMO FNCL CORP",
    location: "CHICAGO, IL",
    charter: "NAT",
    consolidatedAssets: 249342,
    domesticAssets: 249342,
    type: "bank",
    country: "US",
  },
  {
    rank: 15,
    name: "MORGAN STANLEY PRIV BK NA",
    holdingCompany: "MORGAN STANLEY",
    location: "PURCHASE, NY",
    charter: "NAT",
    consolidatedAssets: 240201,
    domesticAssets: 240201,
    type: "bank",
    country: "US",
  },
  {
    rank: 16,
    name: "FIRST-CITIZENS B&TC",
    holdingCompany: "FIRST CITIZENS BSHRS",
    location: "RALEIGH, NC",
    charter: "SNM",
    consolidatedAssets: 233167,
    domesticAssets: 233099,
    type: "bank",
    country: "US",
  },
  {
    rank: 17,
    name: "CITIZENS BK NA",
    holdingCompany: "CITIZENS FNCL GRP",
    location: "PROVIDENCE, RI",
    charter: "NAT",
    consolidatedAssets: 222111,
    domesticAssets: 222111,
    type: "bank",
    country: "US",
  },
  {
    rank: 18,
    name: "FIFTH THIRD BK NA",
    holdingCompany: "FIFTH THIRD BC",
    location: "CINCINNATI, OH",
    charter: "NAT",
    consolidatedAssets: 212207,
    domesticAssets: 212099,
    type: "bank",
    country: "US",
  },
  {
    rank: 19,
    name: "AMERICAN EXPRESS NB",
    holdingCompany: "AMERICAN EXPRESS CO",
    location: "SANDY, UT",
    charter: "NAT",
    consolidatedAssets: 211134,
    domesticAssets: 211134,
    type: "bank",
    country: "US",
  },
  {
    rank: 20,
    name: "MANUFACTURERS & TRADERS TC",
    holdingCompany: "M&T BK CORP",
    location: "BUFFALO, NY",
    charter: "SMB",
    consolidatedAssets: 210742,
    domesticAssets: 210742,
    type: "bank",
    country: "US",
  },
  {
    rank: 21,
    name: "HUNTINGTON NB",
    holdingCompany: "HUNTINGTON BSHRS",
    location: "COLUMBUS, OH",
    charter: "NAT",
    consolidatedAssets: 209541,
    domesticAssets: 209541,
    type: "bank",
    country: "US",
  },
  {
    rank: 22,
    name: "KEYBANK NA",
    holdingCompany: "KEYCORP",
    location: "CLEVELAND, OH",
    charter: "NAT",
    consolidatedAssets: 184695,
    domesticAssets: 184695,
    type: "bank",
    country: "US",
  },
  {
    rank: 23,
    name: "ALLY BK",
    holdingCompany: "ALLY FNCL",
    location: "SANDY, UT",
    charter: "SMB",
    consolidatedAssets: 180089,
    domesticAssets: 180089,
    type: "bank",
    country: "US",
  },
  {
    rank: 24,
    name: "NORTHERN TC",
    holdingCompany: "NORTHERN TR CORP",
    location: "CHICAGO, IL",
    charter: "SMB",
    consolidatedAssets: 169571,
    domesticAssets: 121272,
    type: "bank",
    country: "US",
  },
  {
    rank: 25,
    name: "HSBC BK USA NA",
    holdingCompany: "HSBC N AMER HOLDS",
    location: "TYSONS, VA",
    charter: "NAT",
    consolidatedAssets: 162240,
    domesticAssets: 162240,
    type: "bank",
    country: "US",
  },
  {
    rank: 26,
    name: "REGIONS BK",
    holdingCompany: "REGIONS FC",
    location: "BIRMINGHAM, AL",
    charter: "SMB",
    consolidatedAssets: 158598,
    domesticAssets: 158598,
    type: "bank",
    country: "US",
  },
  {
    rank: 27,
    name: "SANTANDER BK NA",
    holdingCompany: "SANTANDER HOLDS USA",
    location: "WILMINGTON, DE",
    charter: "NAT",
    consolidatedAssets: 97746,
    domesticAssets: 97736,
    type: "bank",
    country: "US",
  },
  {
    rank: 28,
    name: "CITY NB",
    holdingCompany: "RBC US GRP HOLDS LLC",
    location: "LOS ANGELES, CA",
    charter: "NAT",
    consolidatedAssets: 96474,
    domesticAssets: 96474,
    type: "bank",
    country: "US",
  },
  {
    rank: 29,
    name: "FLAGSTAR BK NA",
    holdingCompany: "FLAGSTAR FNCL",
    location: "HICKSVILLE, NY",
    charter: "NAT",
    consolidatedAssets: 91593,
    domesticAssets: 91593,
    type: "bank",
    country: "US",
  },
  {
    rank: 30,
    name: "WESTERN ALLI BK",
    holdingCompany: "WESTERN ALLI BC",
    location: "PHOENIX, AZ",
    charter: "SMB",
    consolidatedAssets: 90816,
    domesticAssets: 90816,
    type: "bank",
    country: "US",
  },
  {
    rank: 31,
    name: "ZIONS BC NA",
    holdingCompany: "",
    location: "SALT LAKE CITY, UT",
    charter: "NAT",
    consolidatedAssets: 88533,
    domesticAssets: 88533,
    type: "bank",
    country: "US",
  },
  {
    rank: 32,
    name: "WEBSTER BK NA",
    holdingCompany: "WEBSTER FNCL CORP",
    location: "STAMFORD, CT",
    charter: "NAT",
    consolidatedAssets: 83097,
    domesticAssets: 83097,
    type: "bank",
    country: "US",
  },
  {
    rank: 33,
    name: "FIRST HORIZON BK",
    holdingCompany: "FIRST HORIZON CORP",
    location: "MEMPHIS, TN",
    charter: "SMB",
    consolidatedAssets: 82887,
    domesticAssets: 82887,
    type: "bank",
    country: "US",
  },
  {
    rank: 34,
    name: "EAST WEST BK",
    holdingCompany: "EAST WEST BC",
    location: "PASADENA, CA",
    charter: "SMB",
    consolidatedAssets: 79082,
    domesticAssets: 75088,
    type: "bank",
    country: "US",
  },
  {
    rank: 35,
    name: "COMERICA BK",
    holdingCompany: "COMERICA",
    location: "DALLAS, TX",
    charter: "SMB",
    consolidatedAssets: 77366,
    domesticAssets: 77045,
    type: "bank",
    country: "US",
  },
  {
    rank: 36,
    name: "UMB BK NA",
    holdingCompany: "UMB FC",
    location: "KANSAS CITY, MO",
    charter: "NAT",
    consolidatedAssets: 71519,
    domesticAssets: 71519,
    type: "bank",
    country: "US",
  },
  {
    rank: 37,
    name: "OLD NB",
    holdingCompany: "OLD NAT BC",
    location: "EVANSVILLE, IN",
    charter: "NAT",
    consolidatedAssets: 70997,
    domesticAssets: 70997,
    type: "bank",
    country: "US",
  },
  {
    rank: 38,
    name: "COLUMBIA BK",
    holdingCompany: "COLUMBIA BKG SYS",
    location: "LAKE OSWEGO, OR",
    charter: "SNM",
    consolidatedAssets: 67491,
    domesticAssets: 67491,
    type: "bank",
    country: "US",
  },
  {
    rank: 39,
    name: "SOUTHSTATE BK NA",
    holdingCompany: "SOUTHSTATE BK CORP",
    location: "WINTER HAVEN, FL",
    charter: "NAT",
    consolidatedAssets: 66028,
    domesticAssets: 66028,
    type: "bank",
    country: "US",
  },
  {
    rank: 40,
    name: "VALLEY NB",
    holdingCompany: "VALLEY NAT BC",
    location: "PASSAIC, NJ",
    charter: "NAT",
    consolidatedAssets: 62959,
    domesticAssets: 62959,
    type: "bank",
    country: "US",
  },
  {
    rank: 41,
    name: "CIBC BK USA",
    holdingCompany: "CIBC BC USA",
    location: "CHICAGO, IL",
    charter: "SMB",
    consolidatedAssets: 61487,
    domesticAssets: 61487,
    type: "bank",
    country: "US",
  },
  {
    rank: 42,
    name: "SYNOVUS BK",
    holdingCompany: "SYNOVUS FC",
    location: "COLUMBUS, GA",
    charter: "SMB",
    consolidatedAssets: 60333,
    domesticAssets: 60333,
    type: "bank",
    country: "US",
  },
  {
    rank: 43,
    name: "PINNACLE BK",
    holdingCompany: "PINNACLE FNCL PTNR",
    location: "NASHVILLE, TN",
    charter: "SNM",
    consolidatedAssets: 55868,
    domesticAssets: 55868,
    type: "bank",
    country: "US",
  },
  {
    rank: 44,
    name: "CADENCE BK",
    holdingCompany: "",
    location: "TUPELO, MS",
    charter: "SMB",
    consolidatedAssets: 53282,
    domesticAssets: 53282,
    type: "bank",
    country: "US",
  },
  {
    rank: 45,
    name: "FROST BK",
    holdingCompany: "CULLEN/FROST BKR",
    location: "SAN ANTONIO, TX",
    charter: "SMB",
    consolidatedAssets: 52599,
    domesticAssets: 52599,
    type: "bank",
    country: "US",
  },
  {
    rank: 46,
    name: "BOKF NA",
    holdingCompany: "BOK FC",
    location: "TULSA, OK",
    charter: "NAT",
    consolidatedAssets: 49918,
    domesticAssets: 49918,
    type: "bank",
    country: "US",
  },
  {
    rank: 47,
    name: "FIRST NB OF PA",
    holdingCompany: "FNB CORP",
    location: "GREENVILLE, PA",
    charter: "NAT",
    consolidatedAssets: 49665,
    domesticAssets: 49665,
    type: "bank",
    country: "US",
  },
  {
    rank: 48,
    name: "BARCLAYS BK DE",
    holdingCompany: "BARCLAYS US LLC",
    location: "WILMINGTON, DE",
    charter: "SNM",
    consolidatedAssets: 46823,
    domesticAssets: 46823,
    type: "bank",
    country: "US",
  },
  {
    rank: 49,
    name: "EVERBANK NA",
    holdingCompany: "EVERBANK FNCL CORP",
    location: "JACKSONVILLE, FL",
    charter: "NAT",
    consolidatedAssets: 44814,
    domesticAssets: 44814,
    type: "bank",
    country: "US",
  },
  {
    rank: 50,
    name: "ASSOCIATED BK NA",
    holdingCompany: "ASSOCIATED BANC-CORP",
    location: "GREEN BAY, WI",
    charter: "NAT",
    consolidatedAssets: 44394,
    domesticAssets: 44394,
    type: "bank",
    country: "US",
  },
  {
    rank: 51,
    name: "RAYMOND JAMES BK",
    holdingCompany: "RAYMOND JAMES FNCL",
    location: "SAINT PETERSBURG, FL",
    charter: "SMB",
    consolidatedAssets: 42857,
    domesticAssets: 42436,
    type: "bank",
    country: "US",
  },
  {
    rank: 52,
    name: "BANK OZK",
    holdingCompany: "",
    location: "LITTLE ROCK, AR",
    charter: "SNM",
    consolidatedAssets: 41607,
    domesticAssets: 41607,
    type: "bank",
    country: "US",
  },
  {
    rank: 53,
    name: "SOFI BK NA",
    holdingCompany: "SOFI TECHS",
    location: "COTTONWOOD HEIGHTS, UT",
    charter: "NAT",
    consolidatedAssets: 41250,
    domesticAssets: 41250,
    type: "bank",
    country: "US",
  },
  {
    rank: 54,
    name: "DEUTSCHE BK TC AMERICAS",
    holdingCompany: "DB USA CORP",
    location: "NEW YORK, NY",
    charter: "SMB",
    consolidatedAssets: 40293,
    domesticAssets: 40293,
    type: "bank",
    country: "US",
  },
  {
    rank: 55,
    name: "PROSPERITY BK",
    holdingCompany: "PROSPERITY BSHRS",
    location: "EL CAMPO, TX",
    charter: "SNM",
    consolidatedAssets: 38360,
    domesticAssets: 38360,
    type: "bank",
    country: "US",
  },
  {
    rank: 56,
    name: "ATLANTIC UNION BK",
    holdingCompany: "ATLANTIC UNION BSHRS CORP",
    location: "RICHMOND, VA",
    charter: "SMB",
    consolidatedAssets: 36991,
    domesticAssets: 36991,
    type: "bank",
    country: "US",
  },
  {
    rank: 57,
    name: "HANCOCK WHITNEY BK",
    holdingCompany: "HANCOCK WHITNEY CORP",
    location: "GULFPORT, MS",
    charter: "SNM",
    consolidatedAssets: 35747,
    domesticAssets: 35747,
    type: "bank",
    country: "US",
  },
  {
    rank: 58,
    name: "BANKUNITED NA",
    holdingCompany: "BANKUNITED",
    location: "MIAMI LAKES, FL",
    charter: "NAT",
    consolidatedAssets: 35065,
    domesticAssets: 35065,
    type: "bank",
    country: "US",
  },
  {
    rank: 59,
    name: "T D BK USA NA",
    holdingCompany: "TD GRP US HOLDS LLC",
    location: "WILMINGTON, DE",
    charter: "NAT",
    consolidatedAssets: 34298,
    domesticAssets: 34298,
    type: "bank",
    country: "US",
  },
  {
    rank: 60,
    name: "BANC OF CA",
    holdingCompany: "BANC OF CA",
    location: "LOS ANGELES, CA",
    charter: "SMB",
    consolidatedAssets: 33924,
    domesticAssets: 33924,
    type: "bank",
    country: "US",
  },
  {
    rank: 61,
    name: "UNITED BK",
    holdingCompany: "UNITED BSHRS",
    location: "FAIRFAX, VA",
    charter: "SMB",
    consolidatedAssets: 33293,
    domesticAssets: 33293,
    type: "bank",
    country: "US",
  },
  {
    rank: 62,
    name: "FIRST NB OF OMAHA",
    holdingCompany: "LAURITZEN CORP",
    location: "OMAHA, NE",
    charter: "NAT",
    consolidatedAssets: 32341,
    domesticAssets: 32341,
    type: "bank",
    country: "US",
  },
  {
    rank: 63,
    name: "TEXAS CAP BK",
    holdingCompany: "TEXAS CAP BSHRS",
    location: "DALLAS, TX",
    charter: "SMB",
    consolidatedAssets: 32246,
    domesticAssets: 32246,
    type: "bank",
    country: "US",
  },
  {
    rank: 64,
    name: "COMMERCE BK",
    holdingCompany: "COMMERCE BSHRS",
    location: "KANSAS CITY, MO",
    charter: "SMB",
    consolidatedAssets: 32081,
    domesticAssets: 32081,
    type: "bank",
    country: "US",
  },
  {
    rank: 65,
    name: "FULTON BK NA",
    holdingCompany: "FULTON FNCL CORP",
    location: "LANCASTER, PA",
    charter: "NAT",
    consolidatedAssets: 31842,
    domesticAssets: 31842,
    type: "bank",
    country: "US",
  },
  {
    rank: 66,
    name: "BNY MELLON NA",
    holdingCompany: "BANK OF NY MELLON CORP",
    location: "PITTSBURGH, PA",
    charter: "NAT",
    consolidatedAssets: 31312,
    domesticAssets: 31312,
    type: "bank",
    country: "US",
  },
  {
    rank: 67,
    name: "GLACIER BK",
    holdingCompany: "GLACIER BC",
    location: "KALISPELL, MT",
    charter: "SNM",
    consolidatedAssets: 28998,
    domesticAssets: 28998,
    type: "bank",
    country: "US",
  },
  {
    rank: 68,
    name: "UNITED CMNTY BK",
    holdingCompany: "UNITED CMNTY BK",
    location: "GREENVILLE, SC",
    charter: "SMB",
    consolidatedAssets: 28088,
    domesticAssets: 28088,
    type: "bank",
    country: "US",
  },
  {
    rank: 69,
    name: "CITY NB OF FL",
    holdingCompany: "BCI FNCL GRP",
    location: "MIAMI, FL",
    charter: "NAT",
    consolidatedAssets: 27771,
    domesticAssets: 27771,
    type: "bank",
    country: "US",
  },
  {
    rank: 70,
    name: "WESBANCO BK",
    holdingCompany: "WESBANCO",
    location: "WHEELING, WV",
    charter: "SNM",
    consolidatedAssets: 27466,
    domesticAssets: 27466,
    type: "bank",
    country: "US",
  },
  {
    rank: 71,
    name: "ARVEST BK",
    holdingCompany: "ARVEST BK GRP",
    location: "FAYETTEVILLE, AR",
    charter: "SMB",
    consolidatedAssets: 27349,
    domesticAssets: 27349,
    type: "bank",
    country: "US",
  },
  {
    rank: 72,
    name: "FIRST INTRST BK",
    holdingCompany: "FIRST INTRST BANCSYSTEM",
    location: "BILLINGS, MT",
    charter: "SMB",
    consolidatedAssets: 27254,
    domesticAssets: 27254,
    type: "bank",
    country: "US",
  },
  {
    rank: 73,
    name: "AMERIS BK",
    holdingCompany: "AMERIS BC",
    location: "ATLANTA, GA",
    charter: "SNM",
    consolidatedAssets: 27014,
    domesticAssets: 27014,
    type: "bank",
    country: "US",
  },
  {
    rank: 74,
    name: "RENASANT BK",
    holdingCompany: "RENASANT CORP",
    location: "TUPELO, MS",
    charter: "SNM",
    consolidatedAssets: 26723,
    domesticAssets: 26723,
    type: "bank",
    country: "US",
  },
  {
    rank: 75,
    name: "WAFD BK",
    holdingCompany: "WAFD",
    location: "SEATTLE, WA",
    charter: "SNM",
    consolidatedAssets: 26683,
    domesticAssets: 26683,
    type: "bank",
    country: "US",
  },
  {
    rank: 76,
    name: "FIRSTBANK",
    holdingCompany: "REISHER FAM FOUND",
    location: "LAKEWOOD, CO",
    charter: "SMB",
    consolidatedAssets: 26621,
    domesticAssets: 26621,
    type: "bank",
    country: "US",
  },
  {
    rank: 77,
    name: "EASTERN BK",
    holdingCompany: "EASTERN BSHRS",
    location: "BOSTON, MA",
    charter: "SNM",
    consolidatedAssets: 25448,
    domesticAssets: 25448,
    type: "bank",
    country: "US",
  },
  {
    rank: 78,
    name: "ROCKLAND TC",
    holdingCompany: "INDEPENDENT BC",
    location: "ROCKLAND, MA",
    charter: "SNM",
    consolidatedAssets: 24993,
    domesticAssets: 24993,
    type: "bank",
    country: "US",
  },
  {
    rank: 79,
    name: "CUSTOMERS BK",
    holdingCompany: "CUSTOMERS BC",
    location: "MALVERN, PA",
    charter: "SMB",
    consolidatedAssets: 24261,
    domesticAssets: 24261,
    type: "bank",
    country: "US",
  },
  {
    rank: 80,
    name: "SIMMONS BK",
    holdingCompany: "SIMMONS FIRST NAT CORP",
    location: "PINE BLUFF, AR",
    charter: "SMB",
    consolidatedAssets: 24164,
    domesticAssets: 24164,
    type: "bank",
    country: "US",
  },
  {
    rank: 81,
    name: "FIRST HAWAIIAN BK",
    holdingCompany: "FIRST HAWAIIAN",
    location: "HONOLULU, HI",
    charter: "SNM",
    consolidatedAssets: 24102,
    domesticAssets: 23391,
    type: "bank",
    country: "US",
  },
  {
    rank: 82,
    name: "CATHAY BK",
    holdingCompany: "CATHAY GEN BC",
    location: "LOS ANGELES, CA",
    charter: "SNM",
    consolidatedAssets: 24059,
    domesticAssets: 23608,
    type: "bank",
    country: "US",
  },
  {
    rank: 83,
    name: "BANK OF HAWAII",
    holdingCompany: "BANK OF HI CORP",
    location: "HONOLULU, HI",
    charter: "SMB",
    consolidatedAssets: 23980,
    domesticAssets: 23407,
    type: "bank",
    country: "US",
  },
  {
    rank: 84,
    name: "BEACON B&TC",
    holdingCompany: "BEACON FC",
    location: "BOSTON, MA",
    charter: "SMB",
    consolidatedAssets: 22780,
    domesticAssets: 22780,
    type: "bank",
    country: "US",
  },
  {
    rank: 85,
    name: "MECHANICS BK",
    holdingCompany: "2011 TCRT",
    location: "WALNUT CREEK, CA",
    charter: "SNM",
    consolidatedAssets: 22713,
    domesticAssets: 22713,
    type: "bank",
    country: "US",
  },
  {
    rank: 86,
    name: "CENTENNIAL BK",
    holdingCompany: "HOME BSHRS",
    location: "CONWAY, AR",
    charter: "SMB",
    consolidatedAssets: 22542,
    domesticAssets: 22542,
    type: "bank",
    country: "US",
  },
  {
    rank: 87,
    name: "TRISTATE CAP BK",
    holdingCompany: "RAYMOND JAMES FNCL",
    location: "PITTSBURGH, PA",
    charter: "SMB",
    consolidatedAssets: 22334,
    domesticAssets: 22334,
    type: "bank",
    country: "US",
  },
  {
    rank: 88,
    name: "TOWNEBANK",
    holdingCompany: "",
    location: "PORTSMOUTH, VA",
    charter: "SNM",
    consolidatedAssets: 19683,
    domesticAssets: 19683,
    type: "bank",
    country: "US",
  },
  {
    rank: 89,
    name: "STIFEL B&T",
    holdingCompany: "STIFEL FNCL CORP",
    location: "SAINT LOUIS, MO",
    charter: "SMB",
    consolidatedAssets: 19672,
    domesticAssets: 19672,
    type: "bank",
    country: "US",
  },
  {
    rank: 90,
    name: "MERCHANTS BK OF IN",
    holdingCompany: "MERCHANTS BC",
    location: "CARMEL, IN",
    charter: "SNM",
    consolidatedAssets: 19297,
    domesticAssets: 19297,
    type: "bank",
    country: "US",
  },
  {
    rank: 91,
    name: "CENTRAL TR BK",
    holdingCompany: "CENTRAL BANCOMPANY INC",
    location: "JEFFERSON CITY, MO",
    charter: "SMB",
    consolidatedAssets: 19188,
    domesticAssets: 19188,
    type: "bank",
    country: "US",
  },
  {
    rank: 92,
    name: "TRUSTMARK BK",
    holdingCompany: "TRUSTMARK CORP",
    location: "JACKSON, MS",
    charter: "SMB",
    consolidatedAssets: 18799,
    domesticAssets: 18799,
    type: "bank",
    country: "US",
  },
  {
    rank: 93,
    name: "FIRST MRCHS BK",
    holdingCompany: "FIRST MRCHS CORP",
    location: "MUNCIE, IN",
    charter: "SNM",
    consolidatedAssets: 18799,
    domesticAssets: 18799,
    type: "bank",
    country: "US",
  },
  {
    rank: 94,
    name: "BANK OF HOPE",
    holdingCompany: "HOPE BC",
    location: "LOS ANGELES, CA",
    charter: "SNM",
    consolidatedAssets: 18501,
    domesticAssets: 18501,
    type: "bank",
    country: "US",
  },
  {
    rank: 95,
    name: "FIRST FNCL BK",
    holdingCompany: "FIRST FNCL BC",
    location: "CINCINNATI, OH",
    charter: "SMB",
    consolidatedAssets: 18457,
    domesticAssets: 18456,
    type: "bank",
    country: "US",
  },
  {
    rank: 96,
    name: "BUSEY BK",
    holdingCompany: "FIRST BUSEY CORP",
    location: "CHAMPAIGN, IL",
    charter: "SMB",
    consolidatedAssets: 18138,
    domesticAssets: 18138,
    type: "bank",
    country: "US",
  },
  {
    rank: 97,
    name: "SERVISFIRST BK",
    holdingCompany: "SERVISFIRST BSHRS",
    location: "HOMEWOOD, AL",
    charter: "SNM",
    consolidatedAssets: 17583,
    domesticAssets: 17583,
    type: "bank",
    country: "US",
  },
  {
    rank: 98,
    name: "SEACOAST NB",
    holdingCompany: "SEACOAST BKG CORP OF FL",
    location: "STUART, FL",
    charter: "NAT",
    consolidatedAssets: 16667,
    domesticAssets: 16667,
    type: "bank",
    country: "US",
  },
  {
    rank: 99,
    name: "COMMUNITY BK NA",
    holdingCompany: "COMMUNITY FNCL SYS",
    location: "CANTON, NY",
    charter: "NAT",
    consolidatedAssets: 16659,
    domesticAssets: 16659,
    type: "bank",
    country: "US",
  },
  {
    rank: 100,
    name: "BANNER BK",
    holdingCompany: "BANNER CORP",
    location: "WALLA WALLA, WA",
    charter: "SNM",
    consolidatedAssets: 16556,
    domesticAssets: 16556,
    type: "bank",
    country: "US",
  },
  {
    rank: 101,
    name: "FIRST UNITED B&TC",
    holdingCompany: "SPEND LIFE WISELY CO",
    location: "DURANT, OK",
    charter: "SMB",
    consolidatedAssets: 16455,
    domesticAssets: 16455,
    type: "bank",
    country: "US",
  },
  {
    rank: 102,
    name: "ENTERPRISE B&TC",
    holdingCompany: "ENTERPRISE FS CORP",
    location: "CLAYTON, MO",
    charter: "SNM",
    consolidatedAssets: 16378,
    domesticAssets: 16378,
    type: "bank",
    country: "US",
  },
  {
    rank: 103,
    name: "FIRSTBANK",
    holdingCompany: "FB FC",
    location: "NASHVILLE, TN",
    charter: "SNM",
    consolidatedAssets: 16201,
    domesticAssets: 16201,
    type: "bank",
    country: "US",
  },
  {
    rank: 104,
    name: "NBT BK NA",
    holdingCompany: "NBT BC",
    location: "NORWICH, NY",
    charter: "NAT",
    consolidatedAssets: 16003,
    domesticAssets: 16003,
    type: "bank",
    country: "US",
  },
  {
    rank: 105,
    name: "CITIZENS BUS BK",
    holdingCompany: "CVB FC",
    location: "ONTARIO, CA",
    charter: "SNM",
    consolidatedAssets: 15670,
    domesticAssets: 15670,
    type: "bank",
    country: "US",
  },
  {
    rank: 106,
    name: "BANK OF AMER CA NA",
    holdingCompany: "BANK OF AMER CORP",
    location: "SAN FRANCISCO, CA",
    charter: "NAT",
    consolidatedAssets: 15015,
    domesticAssets: 15015,
    type: "bank",
    country: "US",
  },
  {
    rank: 107,
    name: "POPULAR BK",
    holdingCompany: "POPULAR",
    location: "NEW YORK, NY",
    charter: "SMB",
    consolidatedAssets: 14940,
    domesticAssets: 14940,
    type: "bank",
    country: "US",
  },
  {
    rank: 108,
    name: "FIRST FNCL BK",
    holdingCompany: "FIRST FNCL BSHRS",
    location: "ABILENE, TX",
    charter: "SMB",
    consolidatedAssets: 14779,
    domesticAssets: 14779,
    type: "bank",
    country: "US",
  },
  {
    rank: 109,
    name: "LIVE OAK BKG CO",
    holdingCompany: "LIVE OAK BSHRS",
    location: "WILMINGTON, NC",
    charter: "SNM",
    consolidatedAssets: 14582,
    domesticAssets: 14582,
    type: "bank",
    country: "US",
  },
  {
    rank: 110,
    name: "DIME CMNTY BK",
    holdingCompany: "DIME CMNTY BSHRS",
    location: "BRIDGEHAMPTON, NY",
    charter: "SMB",
    consolidatedAssets: 14528,
    domesticAssets: 14528,
    type: "bank",
    country: "US",
  },
  {
    rank: 111,
    name: "NEXBANK",
    holdingCompany: "SLHC TR",
    location: "DALLAS, TX",
    charter: "SNM",
    consolidatedAssets: 14443,
    domesticAssets: 14443,
    type: "bank",
    country: "US",
  },
  {
    rank: 112,
    name: "ISRAEL DISCOUNT BK OF NY",
    holdingCompany: "DISCOUNT BC",
    location: "NEW YORK, NY",
    charter: "SNM",
    consolidatedAssets: 14419,
    domesticAssets: 14419,
    type: "bank",
    country: "US",
  },
  {
    rank: 113,
    name: "OCEANFIRST BK NA",
    holdingCompany: "OCEANFIRST FNCL CORP",
    location: "TOMS RIVER, NJ",
    charter: "NAT",
    consolidatedAssets: 14231,
    domesticAssets: 14231,
    type: "bank",
    country: "US",
  },
  {
    rank: 114,
    name: "BELL BK",
    holdingCompany: "STATE BSHRS",
    location: "FARGO, ND",
    charter: "SNM",
    consolidatedAssets: 14135,
    domesticAssets: 14135,
    type: "bank",
    country: "US",
  },
  {
    rank: 115,
    name: "CONNECTONE BK",
    holdingCompany: "CONNECTONE BC",
    location: "ENGLEWOOD CLIFFS, NJ",
    charter: "SNM",
    consolidatedAssets: 14014,
    domesticAssets: 14014,
    type: "bank",
    country: "US",
  },
  {
    rank: 116,
    name: "FIRST BK",
    holdingCompany: "FIRST BC",
    location: "SOUTHERN PINES, NC",
    charter: "SMB",
    consolidatedAssets: 12741,
    domesticAssets: 12741,
    type: "bank",
    country: "US",
  },
  {
    rank: 117,
    name: "VERITEX CMNTY BK",
    holdingCompany: "VERITEX HOLD",
    location: "DALLAS, TX",
    charter: "SMB",
    consolidatedAssets: 12715,
    domesticAssets: 12715,
    type: "bank",
    country: "US",
  },
  {
    rank: 118,
    name: "PLAINSCAPITAL BK",
    holdingCompany: "DIAMOND HTH STOCK CO GP LLC",
    location: "UNIVERSITY PARK, TX",
    charter: "SMB",
    consolidatedAssets: 12641,
    domesticAssets: 12641,
    type: "bank",
    country: "US",
  },
  {
    rank: 119,
    name: "SAFRA NB OF NY",
    holdingCompany: "SNBNY HOLD",
    location: "NEW YORK, NY",
    charter: "NAT",
    consolidatedAssets: 12408,
    domesticAssets: 12388,
    type: "bank",
    country: "US",
  },
  {
    rank: 120,
    name: "FIRST COMMONWEALTH BK",
    holdingCompany: "FIRST COMMONWEALTH FNCL CORP",
    location: "INDIANA, PA",
    charter: "SNM",
    consolidatedAssets: 12279,
    domesticAssets: 12279,
    type: "bank",
    country: "US",
  },
  {
    rank: 121,
    name: "STIFEL BK",
    holdingCompany: "STIFEL FNCL CORP",
    location: "SAINT LOUIS, MO",
    charter: "SMB",
    consolidatedAssets: 11960,
    domesticAssets: 11960,
    type: "bank",
    country: "US",
  },
  {
    rank: 122,
    name: "FIRST FOUND BK",
    holdingCompany: "FIRST FOUND",
    location: "IRVINE, CA",
    charter: "SNM",
    consolidatedAssets: 11886,
    domesticAssets: 11886,
    type: "bank",
    country: "US",
  },
  {
    rank: 123,
    name: "BANCFIRST",
    holdingCompany: "BANCFIRST CORP",
    location: "OKLAHOMA CITY, OK",
    charter: "SMB",
    consolidatedAssets: 11861,
    domesticAssets: 11861,
    type: "bank",
    country: "US",
  },
  {
    rank: 124,
    name: "FARMERS & MRCHS BK LONG BEACH",
    holdingCompany: "PALOMAR ENT LLC",
    location: "LONG BEACH, CA",
    charter: "SMB",
    consolidatedAssets: 11621,
    domesticAssets: 11621,
    type: "bank",
    country: "US",
  },
  {
    rank: 125,
    name: "LENDINGCLUB BK NA",
    holdingCompany: "LENDINGCLUB CORP",
    location: "LEHI, UT",
    charter: "NAT",
    consolidatedAssets: 10967,
    domesticAssets: 10967,
    type: "bank",
    country: "US",
  },
  {
    rank: 126,
    name: "EAGLEBANK",
    holdingCompany: "EAGLE BC",
    location: "BETHESDA, MD",
    charter: "SMB",
    consolidatedAssets: 10764,
    domesticAssets: 10764,
    type: "bank",
    country: "US",
  },
  {
    rank: 127,
    name: "WASHINGTON TR BK",
    holdingCompany: "WTB FC",
    location: "SPOKANE, WA",
    charter: "SNM",
    consolidatedAssets: 10628,
    domesticAssets: 10628,
    type: "bank",
    country: "US",
  },
  {
    rank: 128,
    name: "STELLAR BK",
    holdingCompany: "STELLAR BC",
    location: "HOUSTON, TX",
    charter: "SMB",
    consolidatedAssets: 10627,
    domesticAssets: 10627,
    type: "bank",
    country: "US",
  },
  {
    rank: 129,
    name: "AMERANT BK NA",
    holdingCompany: "AMERANT BC",
    location: "CORAL GABLES, FL",
    charter: "NAT",
    consolidatedAssets: 10387,
    domesticAssets: 10387,
    type: "bank",
    country: "US",
  },
  {
    rank: 130,
    name: "NBH BK",
    holdingCompany: "NATIONAL BK HOLDS CORP",
    location: "GREENWOOD VILLAGE, CO",
    charter: "SMB",
    consolidatedAssets: 10107,
    domesticAssets: 10107,
    type: "bank",
    country: "US",
  },
  {
    rank: 131,
    name: "AMARILLO NB",
    holdingCompany: "AMARILLO NAT BC",
    location: "AMARILLO, TX",
    charter: "NAT",
    consolidatedAssets: 9961,
    domesticAssets: 9961,
    type: "bank",
    country: "US",
  },
  {
    rank: 132,
    name: "CENTIER BK",
    holdingCompany: "FIRST BSHRS",
    location: "MERRILLVILLE, IN",
    charter: "SNM",
    consolidatedAssets: 9918,
    domesticAssets: 9918,
    type: "bank",
    country: "US",
  },
  {
    rank: 133,
    name: "TRI CTY BK",
    holdingCompany: "TRICO BSHRS",
    location: "CHICO, CA",
    charter: "SNM",
    consolidatedAssets: 9875,
    domesticAssets: 9875,
    type: "bank",
    country: "US",
  },
  {
    rank: 134,
    name: "INTERNATIONAL BK OF CMRC",
    holdingCompany: "INTERNATIONAL BSHRS CORP",
    location: "LAREDO, TX",
    charter: "SNM",
    consolidatedAssets: 9847,
    domesticAssets: 9847,
    type: "bank",
    country: "US",
  },
  {
    rank: 135,
    name: "S&T BK",
    holdingCompany: "S&T BC",
    location: "INDIANA, PA",
    charter: "SNM",
    consolidatedAssets: 9812,
    domesticAssets: 9812,
    type: "bank",
    country: "US",
  },
  {
    rank: 136,
    name: "PARK NB",
    holdingCompany: "PARK NAT CORP",
    location: "NEWARK, OH",
    charter: "NAT",
    consolidatedAssets: 9803,
    domesticAssets: 9803,
    type: "bank",
    country: "US",
  },
  {
    rank: 137,
    name: "BYLINE BK",
    holdingCompany: "BYLINE BC",
    location: "CHICAGO, IL",
    charter: "SNM",
    consolidatedAssets: 9791,
    domesticAssets: 9791,
    type: "bank",
    country: "US",
  },
  {
    rank: 138,
    name: "ORIGIN BK",
    holdingCompany: "ORIGIN BC",
    location: "CHOUDRANT, LA",
    charter: "SMB",
    consolidatedAssets: 9689,
    domesticAssets: 9689,
    type: "bank",
    country: "US",
  },
  {
    rank: 139,
    name: "PEOPLES BK",
    holdingCompany: "PEOPLES BC",
    location: "MARIETTA, OH",
    charter: "SMB",
    consolidatedAssets: 9612,
    domesticAssets: 9612,
    type: "bank",
    country: "US",
  },
  {
    rank: 140,
    name: "WINTRUST BK NA",
    holdingCompany: "WINTRUST FC",
    location: "CHICAGO, IL",
    charter: "NAT",
    consolidatedAssets: 9405,
    domesticAssets: 9405,
    type: "bank",
    country: "US",
  },
  {
    rank: 141,
    name: "STOCK YARDS B&TC",
    holdingCompany: "STOCK YARDS BC",
    location: "LOUISVILLE, KY",
    charter: "SNM",
    consolidatedAssets: 9303,
    domesticAssets: 9303,
    type: "bank",
    country: "US",
  },
  {
    rank: 142,
    name: "WOODFOREST NB",
    holdingCompany: "WOODFOREST FNCL GRP ESOP WITH",
    location: "THE WOODLANDS, TX",
    charter: "NAT",
    consolidatedAssets: 9302,
    domesticAssets: 9302,
    type: "bank",
    country: "US",
  },
  {
    rank: 143,
    name: "WELLS FARGO NB WEST",
    holdingCompany: "WELLS FARGO & CO",
    location: "LAS VEGAS, NV",
    charter: "NAT",
    consolidatedAssets: 9289,
    domesticAssets: 9289,
    type: "bank",
    country: "US",
  },
  {
    rank: 144,
    name: "LAKE FOREST B&TC NA",
    holdingCompany: "WINTRUST FC",
    location: "LAKE FOREST, IL",
    charter: "NAT",
    consolidatedAssets: 9242,
    domesticAssets: 8712,
    type: "bank",
    country: "US",
  },
  {
    rank: 145,
    name: "1ST SOURCE BK",
    holdingCompany: "1ST SOURCE CORP",
    location: "SOUTH BEND, IN",
    charter: "SMB",
    consolidatedAssets: 9053,
    domesticAssets: 9053,
    type: "bank",
    country: "US",
  },
  {
    rank: 146,
    name: "NICOLET NB",
    holdingCompany: "NICOLET BSHRS",
    location: "GREEN BAY, WI",
    charter: "NAT",
    consolidatedAssets: 9015,
    domesticAssets: 9015,
    type: "bank",
    country: "US",
  },
  {
    rank: 147,
    name: "UNION B&TC",
    holdingCompany: "FARMERS & MRCH INV",
    location: "LINCOLN, NE",
    charter: "SNM",
    consolidatedAssets: 8882,
    domesticAssets: 8882,
    type: "bank",
    country: "US",
  },
  {
    rank: 148,
    name: "FLUSHING BK",
    holdingCompany: "FLUSHING FC",
    location: "UNIONDALE, NY",
    charter: "SNM",
    consolidatedAssets: 8872,
    domesticAssets: 8872,
    type: "bank",
    country: "US",
  },
  {
    rank: 149,
    name: "AMALGAMATED BK",
    holdingCompany: "WORKERS UNITED",
    location: "NEW YORK, NY",
    charter: "SNM",
    consolidatedAssets: 8686,
    domesticAssets: 8686,
    type: "bank",
    country: "US",
  },
  {
    rank: 150,
    name: "BANCORP BK NA",
    holdingCompany: "BANCORP",
    location: "SIOUX FALLS, SD",
    charter: "NAT",
    consolidatedAssets: 8577,
    domesticAssets: 8577,
    type: "bank",
    country: "US",
  },
  {
    rank: 151,
    name: "PINNACLE BK",
    holdingCompany: "PINNACLE BC",
    location: "LINCOLN, NE",
    charter: "SNM",
    consolidatedAssets: 8567,
    domesticAssets: 8567,
    type: "bank",
    country: "US",
  },
  {
    rank: 152,
    name: "UNIVEST B&TC",
    holdingCompany: "UNIVEST FC",
    location: "HILLTOWN, PA",
    charter: "SMB",
    consolidatedAssets: 8545,
    domesticAssets: 8545,
    type: "bank",
    country: "US",
  },
  {
    rank: 153,
    name: "SUNFLOWER BK NA",
    holdingCompany: "FIRSTSUN CAP BC",
    location: "DALLAS, TX",
    charter: "NAT",
    consolidatedAssets: 8482,
    domesticAssets: 8482,
    type: "bank",
    country: "US",
  },
  {
    rank: 154,
    name: "FIRST SECURITY BK",
    holdingCompany: "FIRST SECURITY BANCORP",
    location: "SEARCY, AR",
    charter: "SMB",
    consolidatedAssets: 8460,
    domesticAssets: 8460,
    type: "bank",
    country: "US",
  },
  {
    rank: 155,
    name: "TOMPKINS CMNTY BK",
    holdingCompany: "TOMPKINS FNCL CORP",
    location: "ITHACA, NY",
    charter: "SNM",
    consolidatedAssets: 8431,
    domesticAssets: 8431,
    type: "bank",
    country: "US",
  },
  {
    rank: 156,
    name: "SALEM FIVE CENTS SVG BK",
    holdingCompany: "SALEM FIVE BC",
    location: "SALEM, MA",
    charter: "SNM",
    consolidatedAssets: 8426,
    domesticAssets: 8426,
    type: "bank",
    country: "US",
  },
  {
    rank: 157,
    name: "GERMAN AMER BK",
    holdingCompany: "GERMAN AMER BC",
    location: "JASPER, IN",
    charter: "SNM",
    consolidatedAssets: 8388,
    domesticAssets: 8388,
    type: "bank",
    country: "US",
  },
  {
    rank: 158,
    name: "SOUTHSIDE BK",
    holdingCompany: "SOUTHSIDE BSHRS",
    location: "TYLER, TX",
    charter: "SNM",
    consolidatedAssets: 8376,
    domesticAssets: 8376,
    type: "bank",
    country: "US",
  },
  {
    rank: 159,
    name: "METROPOLITAN CMRL BK",
    holdingCompany: "METROPOLITAN BK HOLD CORP",
    location: "NEW YORK, NY",
    charter: "SMB",
    consolidatedAssets: 8233,
    domesticAssets: 8233,
    type: "bank",
    country: "US",
  },
  {
    rank: 160,
    name: "CNB BK",
    holdingCompany: "CNB FC",
    location: "CLEARFIELD, PA",
    charter: "SNM",
    consolidatedAssets: 8232,
    domesticAssets: 8232,
    type: "bank",
    country: "US",
  },
  {
    rank: 161,
    name: "CROSS RIVER BK",
    holdingCompany: "CRB GRP",
    location: "FORT LEE, NJ",
    charter: "SNM",
    consolidatedAssets: 8120,
    domesticAssets: 8111,
    type: "bank",
    country: "US",
  },
  {
    rank: 162,
    name: "FIRST AMER BK",
    holdingCompany: "FIRST AMER BK CORP",
    location: "ELK GROVE VILLAGE, IL",
    charter: "SNM",
    consolidatedAssets: 8071,
    domesticAssets: 8071,
    type: "bank",
    country: "US",
  },
  {
    rank: 163,
    name: "B1BANK",
    holdingCompany: "BUSINESS FIRST BSHRS",
    location: "BATON ROUGE, LA",
    charter: "SNM",
    consolidatedAssets: 7947,
    domesticAssets: 7947,
    type: "bank",
    country: "US",
  },
  {
    rank: 164,
    name: "BANKPLUS",
    holdingCompany: "BANCPLUS CORP",
    location: "BELZONI, MS",
    charter: "SNM",
    consolidatedAssets: 7915,
    domesticAssets: 7915,
    type: "bank",
    country: "US",
  },
  {
    rank: 165,
    name: "BURKE & HERBERT B&TC",
    holdingCompany: "BURKE & HERBERT FS CORP",
    location: "ALEXANDRIA, VA",
    charter: "SMB",
    consolidatedAssets: 7871,
    domesticAssets: 7871,
    type: "bank",
    country: "US",
  },
  {
    rank: 166,
    name: "HANMI BK",
    holdingCompany: "HANMI FC",
    location: "LOS ANGELES, CA",
    charter: "SNM",
    consolidatedAssets: 7812,
    domesticAssets: 7812,
    type: "bank",
    country: "US",
  },
  {
    rank: 167,
    name: "FIRST MID B&TC NA",
    holdingCompany: "FIRST MID BSHRS",
    location: "MATTOON, IL",
    charter: "NAT",
    consolidatedAssets: 7769,
    domesticAssets: 7769,
    type: "bank",
    country: "US",
  },
  {
    rank: 168,
    name: "FORBRIGHT BK",
    holdingCompany: "FORBRIGHT",
    location: "POTOMAC, MD",
    charter: "SNM",
    consolidatedAssets: 7693,
    domesticAssets: 7693,
    type: "bank",
    country: "US",
  },
  {
    rank: 169,
    name: "SMBC MANUBANK",
    holdingCompany: "SMBC AMERS HOLDS",
    location: "LOS ANGELES, CA",
    charter: "SNM",
    consolidatedAssets: 7505,
    domesticAssets: 7505,
    type: "bank",
    country: "US",
  },
  {
    rank: 170,
    name: "BANKERS TC",
    holdingCompany: "BTC FC",
    location: "DES MOINES, IA",
    charter: "SNM",
    consolidatedAssets: 7493,
    domesticAssets: 7493,
    type: "bank",
    country: "US",
  },
  {
    rank: 171,
    name: "PREFERRED BK",
    holdingCompany: "",
    location: "LOS ANGELES, CA",
    charter: "SNM",
    consolidatedAssets: 7468,
    domesticAssets: 7468,
    type: "bank",
    country: "US",
  },
  {
    rank: 172,
    name: "BANK OF COLORADO",
    holdingCompany: "PINNACLE BC",
    location: "FORT COLLINS, CO",
    charter: "SNM",
    consolidatedAssets: 7438,
    domesticAssets: 7438,
    type: "bank",
    country: "US",
  },
  {
    rank: 173,
    name: "PEAPACK PRIV B&TC",
    holdingCompany: "PEAPACK-GLADSTONE FC",
    location: "BEDMINSTER, NJ",
    charter: "SMB",
    consolidatedAssets: 7436,
    domesticAssets: 7436,
    type: "bank",
    country: "US",
  },
  {
    rank: 174,
    name: "RBC BK GA NA",
    holdingCompany: "RBC US GRP HOLDS LLC",
    location: "ATLANTA, GA",
    charter: "NAT",
    consolidatedAssets: 7422,
    domesticAssets: 7422,
    type: "bank",
    country: "US",
  },
  {
    rank: 175,
    name: "CENTRAL PACIFIC BK",
    holdingCompany: "CENTRAL PACIFIC FC",
    location: "HONOLULU, HI",
    charter: "SMB",
    consolidatedAssets: 7415,
    domesticAssets: 7415,
    type: "bank",
    country: "US",
  },
  {
    rank: 176,
    name: "OCEAN BK",
    holdingCompany: "OCEAN BSHRS",
    location: "MIAMI, FL",
    charter: "SNM",
    consolidatedAssets: 7396,
    domesticAssets: 7396,
    type: "bank",
    country: "US",
  },
  {
    rank: 177,
    name: "POPPY BK",
    holdingCompany: "BIG POPPY HOLDS",
    location: "SANTA ROSA, CA",
    charter: "SNM",
    consolidatedAssets: 7317,
    domesticAssets: 7317,
    type: "bank",
    country: "US",
  },
  {
    rank: 178,
    name: "COMENITY BK",
    holdingCompany: "",
    location: "WILMINGTON, DE",
    charter: "SNM",
    consolidatedAssets: 7308,
    domesticAssets: 7308,
    type: "bank",
    country: "US",
  },
  {
    rank: 179,
    name: "STOCKMAN BK OF MT",
    holdingCompany: "STOCKMAN FC",
    location: "MILES CITY, MT",
    charter: "SNM",
    consolidatedAssets: 7169,
    domesticAssets: 7169,
    type: "bank",
    country: "US",
  },
  {
    rank: 180,
    name: "PATHWARD NA",
    holdingCompany: "PATHWARD FNCL",
    location: "SIOUX FALLS, SD",
    charter: "NAT",
    consolidatedAssets: 7167,
    domesticAssets: 7167,
    type: "bank",
    country: "US",
  },
  {
    rank: 181,
    name: "JOHNSON BK",
    holdingCompany: "JOHNSON FNCL GRP",
    location: "RACINE, WI",
    charter: "SMB",
    consolidatedAssets: 7069,
    domesticAssets: 7069,
    type: "bank",
    country: "US",
  },
  {
    rank: 182,
    name: "REPUBLIC B&TC",
    holdingCompany: "REPUBLIC BANCORP",
    location: "LOUISVILLE, KY",
    charter: "SNM",
    consolidatedAssets: 7009,
    domesticAssets: 7009,
    type: "bank",
    country: "US",
  },
  {
    rank: 183,
    name: "HERITAGE BK",
    holdingCompany: "HERITAGE FC",
    location: "OLYMPIA, WA",
    charter: "SNM",
    consolidatedAssets: 7006,
    domesticAssets: 7006,
    type: "bank",
    country: "US",
  },
  {
    rank: 184,
    name: "OLD SECOND NB",
    holdingCompany: "OLD SECOND BC",
    location: "AURORA, IL",
    charter: "NAT",
    consolidatedAssets: 6982,
    domesticAssets: 6982,
    type: "bank",
    country: "US",
  },
  {
    rank: 185,
    name: "CAMDEN NB",
    holdingCompany: "CAMDEN NAT CORP",
    location: "CAMDEN, ME",
    charter: "NAT",
    consolidatedAssets: 6970,
    domesticAssets: 6970,
    type: "bank",
    country: "US",
  },
  {
    rank: 186,
    name: "CAMBRIDGE SVG BK",
    holdingCompany: "CAMBRIDGE FNCL GROUP",
    location: "CAMBRIDGE, MA",
    charter: "SNM",
    consolidatedAssets: 6950,
    domesticAssets: 6950,
    type: "bank",
    country: "US",
  },
  {
    rank: 187,
    name: "MIDLAND ST BK",
    holdingCompany: "MIDLAND STATES BANCORP",
    location: "EFFINGHAM, IL",
    charter: "SMB",
    consolidatedAssets: 6903,
    domesticAssets: 6903,
    type: "bank",
    country: "US",
  },
  {
    rank: 188,
    name: "LAKE CITY BK",
    holdingCompany: "LAKELAND FC",
    location: "WARSAW, IN",
    charter: "SMB",
    consolidatedAssets: 6894,
    domesticAssets: 6894,
    type: "bank",
    country: "US",
  },
  {
    rank: 189,
    name: "NORTHPOINTE BK",
    holdingCompany: "NORTHPOINTE BSHRS",
    location: "GRAND RAPIDS, MI",
    charter: "SNM",
    consolidatedAssets: 6839,
    domesticAssets: 6839,
    type: "bank",
    country: "US",
  },
  {
    rank: 190,
    name: "ALPINE BK",
    holdingCompany: "ALPINE BK OF CO",
    location: "GLENWOOD SPRINGS, CO",
    charter: "SNM",
    consolidatedAssets: 6816,
    domesticAssets: 6816,
    type: "bank",
    country: "US",
  },
  {
    rank: 191,
    name: "INTRUST BK NA",
    holdingCompany: "INTRUST FC",
    location: "WICHITA, KS",
    charter: "NAT",
    consolidatedAssets: 6804,
    domesticAssets: 6804,
    type: "bank",
    country: "US",
  },
  {
    rank: 192,
    name: "WASHINGTON TC OF WESTERLY",
    holdingCompany: "WASHINGTON TR BC",
    location: "WESTERLY, RI",
    charter: "SNM",
    consolidatedAssets: 6720,
    domesticAssets: 6720,
    type: "bank",
    country: "US",
  },
  {
    rank: 193,
    name: "HORIZON BK",
    holdingCompany: "HORIZON BC",
    location: "MICHIGAN CITY, IN",
    charter: "SNM",
    consolidatedAssets: 6692,
    domesticAssets: 6692,
    type: "bank",
    country: "US",
  },
  {
    rank: 194,
    name: "CITY NB OF WV",
    holdingCompany: "CITY HC",
    location: "CHARLESTON, WV",
    charter: "NAT",
    consolidatedAssets: 6649,
    domesticAssets: 6649,
    type: "bank",
    country: "US",
  },
  {
    rank: 195,
    name: "COMMUNITY TR BK INC",
    holdingCompany: "COMMUNITY TR BC",
    location: "PIKEVILLE, KY",
    charter: "SMB",
    consolidatedAssets: 6597,
    domesticAssets: 6597,
    type: "bank",
    country: "US",
  },
  {
    rank: 196,
    name: "MIZUHO BK USA",
    holdingCompany: "MIZUHO AMERS LLC",
    location: "NEW YORK, NY",
    charter: "SMB",
    consolidatedAssets: 6595,
    domesticAssets: 6595,
    type: "bank",
    country: "US",
  },
  {
    rank: 197,
    name: "FIRST BK",
    holdingCompany: "FB CORP",
    location: "CREVE COEUR, MO",
    charter: "SMB",
    consolidatedAssets: 6569,
    domesticAssets: 6569,
    type: "bank",
    country: "US",
  },
  {
    rank: 198,
    name: "FIRST NB AMER",
    holdingCompany: "FIRST NAT BSHRS",
    location: "EAST LANSING, MI",
    charter: "NAT",
    consolidatedAssets: 6569,
    domesticAssets: 6569,
    type: "bank",
    country: "US",
  },
  {
    rank: 199,
    name: "EQUITY BK",
    holdingCompany: "EQUITY BSHRS",
    location: "ANDOVER, KS",
    charter: "SMB",
    consolidatedAssets: 6356,
    domesticAssets: 6356,
    type: "bank",
    country: "US",
  },
  {
    rank: 200,
    name: "SHORE UNITED BK NA",
    holdingCompany: "SHORE BSHRS",
    location: "EASTON, MD",
    charter: "NAT",
    consolidatedAssets: 6276,
    domesticAssets: 6276,
    type: "bank",
    country: "US",
  },
]
